### ISSUE TITLE
[meta] Servo blockers

### ISSUE THREAD

**Issue by fabricedesre** [fabricedesre/servonk#7]
These are Servo issues that are blocking servonk one way or the other from being awesome:
- [ ] https://github.com/servo/servo/issues/20822 : Flex layout is not updated on window resize. That prevents the layout of the status and navbars to update properly on window resize.
- [ ] https://github.com/servo/servo/issues/20379 : The `Idle` state is not always reached at the end of css transitions. Many animations are disabled because of that bug.
- [ ] https://github.com/servo/servo/issues/20731 : Keyframe animations are not stopped/removed properly. That is preventing us from using keyframe animations without using a crazy amount of cpu.
- [ ] https://github.com/servo/servo/issues/20660 : Add a ThemeColorChanged embedder message. Needed to implement ambient themeing.
- [ ] https://github.com/servo/servo/issues/20284 : The :active pseudo class is not (fully) supported. That forces us to manually set classes on tapped elements to eg. change the background color (see the lockscreen code).
- [ ] https://github.com/servo/servo/issues/20111 : Full page flexbox layout doesn't fill the page. Maybe we could have a simpler page layout if that worked.

**Comment by gterzian** [comment]
The BroadcastChannel part is now done...
